#debug: true
#
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost/security_demo
#    username: root
#    password: pass123
#    initialize: true
#    schema: classpath:schema.sql
#    name: spring_demo
#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQLDialect
#    show-sql: true
#server:
#  ssl:
#    enabled: true   # config in SecurityConfig is also needed.
#    key-store: keystore.jks    # public key for TLS. Generate it via README.md
#    key-store-password: password
#    client-auth: want
#    protocol: TLSv1
#
